spectaql:
  displayAllServers: true
  faviconFile: favicon.ico
  logoFile: logo.png

introspection:
  url: http://localhost:8080/graphql
  metadataFile: ./metadata.json
  removeTrailingPeriodFromDescriptions: false
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 1
  hideQueriesWithUndocumentedReturnType: true

extensions:
  graphqlScalarExamples: true

info:
  title: BEB Social SDK
  description: Use our GraphQL endpoints with your language of choice ðŸ˜Ž Also see our protocol docs at [docs.beb.xyz](https://docs.beb.xyz). <br/>Want to contribute to our SDK? Find the code at [github.com/bebdotxyz/beb-sdk](https://github.com/bebdotxyz/beb-sdk)
  x-hidePoweredBy: true
  contact:
    email: gm@beb.xyz
    url: https://docs.beb.xyz
  x-introItems:
    - title: Initialization
      file: ./init.md
    - title: Authentication
      file: ./auth.md

servers:
  - url: https://protocol.beb.xyz/graphql
    description: Production
    production: true
